# Generated by Django 5.2.16 on 2026-07-09 07:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import inventory.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='Название шкафа')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
            ],
            options={
                'verbose_name': 'коммутационный шкаф',
                'verbose_name_plural': 'коммутационные шкафы',
                'ordering': ['location__organization__name', 'location__address', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Категория')),
                ('code', models.CharField(help_text='Например: N, W, M, SW', max_length=8, unique=True, verbose_name='Код категории')),
                ('tracking_mode', models.CharField(choices=[('unit', 'Поштучно'), ('quantity', 'Количественно')], default='unit', max_length=20, verbose_name='Способ учёта')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('position', models.CharField(blank=True, max_length=255, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('archived', models.BooleanField(default=False, verbose_name='Уволен / в архиве')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'сотрудник',
                'verbose_name_plural': 'сотрудники',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('label', models.CharField(blank=True, help_text='Например: Главный офис', max_length=150, verbose_name='Краткое название')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
            ],
            options={
                'verbose_name': 'адрес',
                'verbose_name_plural': 'адреса',
                'ordering': ['organization__name', 'address'],
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('short_name', models.CharField(blank=True, max_length=100, verbose_name='Краткое наименование')),
                ('prefix', models.CharField(help_text='Например: FOX или SZ', max_length=12, unique=True, verbose_name='Префикс кодов')),
                ('kind', models.CharField(choices=[('company', 'Организация'), ('personal', 'Личное имущество'), ('client', 'Клиентская организация')], default='company', max_length=20, verbose_name='Тип')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'организация/владелец',
                'verbose_name_plural': 'организации и владельцы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('internal_code', models.CharField(blank=True, max_length=80, unique=True, verbose_name='Внутренний номер')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('manufacturer', models.CharField(blank=True, max_length=150, verbose_name='Производитель')),
                ('model', models.CharField(blank=True, max_length=180, verbose_name='Модель')),
                ('serial_number', models.CharField(blank=True, max_length=180, verbose_name='Серийный номер')),
                ('hostname', models.CharField(blank=True, max_length=180, verbose_name='Hostname')),
                ('freeform_location', models.CharField(blank=True, max_length=500, verbose_name='Место установки (текстом)')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество')),
                ('usage_status', models.CharField(choices=[('stock', 'На складе'), ('employee', 'Выдано сотруднику'), ('object', 'Установлено на объекте'), ('repair', 'В ремонте'), ('reserve', 'В резерве'), ('waiting_disposal', 'Ждёт списания'), ('disposed', 'Списано'), ('loaned', 'Временно передано другой организации')], default='stock', max_length=30, verbose_name='Статус')),
                ('condition', models.CharField(choices=[('new', 'Новое'), ('used', 'Б/У'), ('broken', 'Сломано')], default='new', max_length=20, verbose_name='Состояние')),
                ('notes', models.TextField(blank=True, verbose_name='Описание / комментарий')),
                ('network_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес управления')),
                ('network_username', models.CharField(blank=True, max_length=255, verbose_name='Логин')),
                ('network_password_encrypted', models.TextField(blank=True, editable=False, verbose_name='Зашифрованный пароль')),
                ('archived', models.BooleanField(default=False, verbose_name='В архиве')),
                ('cabinet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.cabinet', verbose_name='Коммутационный шкаф')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.category', verbose_name='Категория')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.employee', verbose_name='Ответственный сотрудник')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='inventory.location', verbose_name='Адрес установки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_equipment', to='inventory.organization', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'оборудование',
                'verbose_name_plural': 'оборудование',
                'ordering': ['internal_code', 'name'],
            },
        ),
        migrations.AddField(
            model_name='cabinet',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cabinets', to='inventory.location', verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='inventory.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='EquipmentMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('created', 'Создание карточки'), ('edited', 'Изменение карточки'), ('assigned', 'Выдача сотруднику'), ('returned', 'Возврат'), ('installed', 'Установка на объекте'), ('loaned', 'Передача другой организации'), ('loan_return', 'Возврат владельцу'), ('repair', 'Передача в ремонт'), ('disposed', 'Списание'), ('act', 'Операция по акту'), ('import', 'Импорт')], max_length=30, verbose_name='Тип операции')),
                ('from_status', models.CharField(blank=True, max_length=30, verbose_name='Предыдущий статус')),
                ('to_status', models.CharField(blank=True, max_length=30, verbose_name='Новый статус')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='inventory.equipment', verbose_name='Оборудование')),
                ('from_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='inventory.employee', verbose_name='От сотрудника')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='inventory.employee', verbose_name='К сотруднику')),
                ('from_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_from', to='inventory.organization', verbose_name='От организации')),
                ('to_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_to', to='inventory.organization', verbose_name='К организации')),
            ],
            options={
                'verbose_name': 'операция с оборудованием',
                'verbose_name_plural': 'история оборудования',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата передачи')),
                ('expected_return_at', models.DateField(blank=True, null=True, verbose_name='Плановая дата возврата')),
                ('returned_at', models.DateField(blank=True, null=True, verbose_name='Дата возврата')),
                ('undocumented', models.BooleanField(default=True, verbose_name='Передача без документов')),
                ('document', models.FileField(blank=True, upload_to='loans/%Y/%m/', validators=[inventory.validators.validate_document], verbose_name='Документ')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('active', 'Активна'), ('returned', 'Возвращено')], default='active', max_length=20, verbose_name='Статус')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='inventory.equipment', verbose_name='Оборудование')),
                ('responsible_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_loans', to='inventory.employee', verbose_name='Ответственный')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans_received', to='inventory.organization', verbose_name='Получатель')),
                ('lender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans_given', to='inventory.organization', verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'временная передача',
                'verbose_name_plural': 'временные передачи',
                'ordering': ['-started_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='inventory.organization', verbose_name='Организация'),
        ),
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=100, verbose_name='Номер акта')),
                ('act_type', models.CharField(choices=[('issue', 'Выдача оборудования'), ('return', 'Возврат оборудования'), ('transfer', 'Передача между организациями'), ('other', 'Другой акт')], default='issue', max_length=20, verbose_name='Тип акта')),
                ('act_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата акта')),
                ('document', models.FileField(upload_to='acts/%Y/%m/', validators=[inventory.validators.validate_document], verbose_name='Скан акта')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('public_enabled', models.BooleanField(default=False, verbose_name='Разрешить просмотр по секретной ссылке')),
                ('public_token', models.CharField(blank=True, editable=False, max_length=64, unique=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acts', to='inventory.employee', verbose_name='Сотрудник')),
                ('equipment', models.ManyToManyField(blank=True, related_name='acts', to='inventory.equipment', verbose_name='Оборудование')),
                ('from_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acts_from', to='inventory.organization', verbose_name='Передающая организация')),
                ('to_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acts_to', to='inventory.organization', verbose_name='Получающая организация')),
            ],
            options={
                'verbose_name': 'акт',
                'verbose_name_plural': 'акты',
                'ordering': ['-act_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepairRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opened_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата передачи')),
                ('closed_at', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('problem', models.TextField(blank=True, verbose_name='Описание неисправности')),
                ('result', models.TextField(blank=True, verbose_name='Результат')),
                ('status', models.CharField(choices=[('open', 'В ремонте'), ('done', 'Завершён'), ('unrepairable', 'Не подлежит ремонту')], default='open', max_length=20, verbose_name='Статус')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repairs', to='inventory.equipment', verbose_name='Оборудование')),
            ],
            options={
                'verbose_name': 'ремонт',
                'verbose_name_plural': 'ремонты',
                'ordering': ['-opened_at', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='cabinet',
            constraint=models.UniqueConstraint(fields=('location', 'name'), name='uniq_location_cabinet'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('organization', 'address'), name='uniq_org_address'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['internal_code'], name='inventory_e_interna_c61283_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['serial_number'], name='inventory_e_serial__97e65d_idx'),
        ),
        migrations.AddIndex(
            model_name='equipment',
            index=models.Index(fields=['hostname'], name='inventory_e_hostnam_8fc3e8_idx'),
        ),
    ]
